### ISSUE TITLE
Feature: .YML file for pokemon color palettes

### ISSUE THREAD

**Issue by dweipert-3138720606** [klauscfhq/hyper-pokemon#1]
Wouldn't it be cleaner if a yml file is used to update the list of color palettes? This way a `random` theme could already be implemented by just selecting a random index from the array of pokemon in the yml file.

**Comment by klaudiosinani** [comment]
That's definitely an upcoming feature 😃 
The project was initialized just last night, that's why everything is done through the `index.js` file 😄  
In addition, features like a `random pokemon background`, or a `random pokemon background` based on a specific `pokemon region` we be added really really soon. Right now our main goal is to release as many as possible themes with a nice and user friendly color-syntax. Thanks a ton for dropping by and reporting it & you are more than welcome to contribute if you feel like it : )

**Comment by dweipert-3138720606** [comment]
Can do, will do. Got time to do this by tomorrow evening CET. :)
