### ISSUE TITLE
Add transparency

### ISSUE THREAD

**Issue by dweipert-3138720606** [klauscfhq/hyper-pokemon#4]
Having a transparent background / terminal would be awesome.

I don't know what's the best way to do this yet, as the images themself are not transparent, but maybe with some css quirks it can be made transparent without affecting the text inside the terminal.

**Comment by klaudiosinani** [comment]
Yep it would be super awesome! But, for now it's not a native feature of Electron and it might take some time to be implemented by the Electron team and then the Hyper one. Though we definitely keep an eye on it! It's definitely on our wish list! 😄 Thank you again for taking the time to propose it!

**Comment by klaudiosinani** [comment]
**Update:** Using the method described [here](https://github.com/zeit/hyper/issues/1638#issuecomment-285934623) you can implement transparency on Windows/Linux but it wouldn't be something that you could do straight from the plugin 😄 We just have to wait for the Hyper team to bring it back as it used to exist in the past, they probably pulled it back because it did not integrate that well with these two OS-s environments (because of Electron related issues i guess). Once it's released it will be integrated by us in a flash! 😄
